version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/code
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - DATABASE_URL=postgresql://user:password@db/dbname
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname

volumes:
  postgres_data: